### PR TITLE
fix(ButtonGroup): Set style background color to ButtonGroup

### LINKED ISSUE #1011: ButtonGroup blue background
### Description

1. Used `ButtonGroup`
2. Can disable blue color behind button element
3. Once you will set `borderRadius` to buttonStyle - blue color behind will appear.

`v1.0.0-beta3`

### Reproduction Steps and Sample Code

```JavaScript
render() {
        return (
            <View style={styles.container}>
                <ButtonGroup
                    onPress={this.updateIndex.bind(this)}
                    selectedIndex={this.state.tab}
                    buttons={buttons}
                    containerStyle={styles.containerStyle}
                    buttonStyle={styles.buttonStyle}
                    selectedButtonStyle={styles.selectedButtonStyle}
                    innerBorderStyle={{width: 0, color: colorScheme.white}}
                    containerBorderRadius={0}
                    underlayColor={colorScheme.gray}
                />
            </View>

        );
    }
.......

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    containerStyle: {
        height: 50,
        width: '100%',
        // borderTopRightRadius: 20,
        borderWidth: 0,
        backgroundColor: colorScheme.white,
        marginTop: 0,
        borderRadius: 0
    },
    buttonStyle: {
        backgroundColor: colorScheme.white,
        borderTopRightRadius: 20,
        borderTopLeftRadius: 20,
        borderWidth: 0,
    },
    selectedButtonStyle: {
        backgroundColor: colorScheme.gray,
    }
});
```

image

### PR DESCRIPTION
**Pull request by dincozdemir**
Closes  #1011

### CODE REVIEW

File: src/buttons/ButtonGroup.js [hunk 1]
```diff
@@ -95,7 +98,10 @@ const ButtonGroup = props => {
                 borderBottomLeftRadius: containerBorderRadius,
               },
               isSelected && {
-                backgroundColor: colors.primary,
+                backgroundColor:
+                  (buttonStyleObj && buttonStyleObj.backgroundColor) ||
+                  (containerStyleObj && containerStyleObj.backgroundColor) ||
+                  colors.primary,
               },
```
Comment (xavier-villelegier) [inline src/buttons/ButtonGroup.js]: I think you just need to move the
```
isSelected && {
  backgroundColor: colors.primary,
},
```

from the `Component` to the `View` just below ([line 102](https://github.com/react-native-training/react-native-elements/pull/1040/files#diff-6bc2a6e42a02b3c01d6f4ccaf34c94cfL102))

Comment (dincozdemir) [reply src/buttons/ButtonGroup.js]: Thanks for the warning. fixing it right away.

**Comment by dincozdemir** [comment]
@xavier-villelegier Does this seem right?
