### PR TITLE
fix(Button): Make the padding consistent

### LINKED ISSUE #1427: Buttons with only icon have different padding than buttons with text
**Explain what you did**
I tried to create multiple buttons of which some have text and some have only icon. 

**Expected behaviour**
I expected all buttons to have the same padding. It would be great if all the buttons had the same padding out of the box without having to write custom styles.

**Describe the bug**
Buttons with only icon have smaller padding (no padding?) and it makes them different size than other buttons.

**To Reproduce**
Relevant part of code:
```javascript
<Button title='' icon={{ name: 'minus', type: 'font-awesome' }} />
<Button title='RESET' />
<Button title='' icon={{ name: 'plus', type: 'font-awesome' }} />
<Button title='ADD' icon={{ name: 'plus', type: 'font-awesome' }} />
```

https://snack.expo.io/@apaatsio/petrified-chip

**Possible Solution**
Add padding to buttons that have only icon.

**Screenshots**
react-native-elements icon buttons size diff

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta5 |
| expo | 30.0.0 |
| npm | 5.6.0 |

### PR DESCRIPTION
**Pull request by haruelrovix**
They have the same `height` now.

|Before|After|
|-|-|
|screenshot_2018-10-23-22-09-11-543_com a|screenshot_2018-10-23-22-39-29-935_com a|

Fix #1427 .

### CODE REVIEW

**Comment by haruelrovix** [comment]
More details:

|-|Reset|
|-|-|
|screenshot_2018-10-23-22-38-51-399_com a|screenshot_2018-10-23-22-38-59-590_com a|

|+|Add|
|-|-|
|screenshot_2018-10-23-22-39-06-107_com a|screenshot_2018-10-23-22-39-17-334_com a|

**Comment by haruelrovix** [comment]
@xavier-villelegier achieved the same looks via this, [1c413dd](https://github.com/react-native-training/react-native-elements/pull/1505/commits/1c413dd06af90470687affcbb870ad914c91b6ce).

Preview:

File: src/buttons/Button.js [hunk 1]
```diff
@@ -199,7 +200,8 @@ const styles = {
     color: 'white',
     fontSize: 16,
     textAlign: 'center',
-    padding: 8,
+    paddingTop: 2,
+    paddingBottom: 1,
```
Comment (xavier-villelegier) [inline src/buttons/Button.js]: Was just wondering why did you put padding on the `title` ?

Comment (xavier-villelegier) [reply src/buttons/Button.js]: Okay the goal is to have all button of the same height. Looks good to me then.

**Comment by iRoachie** [comment]
Hey @haruelrovix  can you rebase your PR from the `next` branch? It has a ton of additional commits?

**Comment by haruelrovix** [comment]
@iRoachie please ignore my previous comment. `rebase` is done 🤝

**Comment by iRoachie** [comment]
Thank youuuuu 💯
